name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the node version compatible with your project

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Change this if your build command is different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        publish_dir: ./dist  # Change this to your build output directory
